// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getZone(args?: GetZoneArgs, opts?: pulumi.InvokeOptions): Promise<GetZoneResult> {
    args = args || {};
    return pulumi.runtime.invoke("aws:route53/getZone:getZone", {
        "callerReference": args.callerReference,
        "comment": args.comment,
        "name": args.name,
        "privateZone": args.privateZone,
        "resourceRecordSetCount": args.resourceRecordSetCount,
        "tags": args.tags,
        "vpcId": args.vpcId,
        "zoneId": args.zoneId,
    }, opts);
}

/**
 * A collection of arguments for invoking getZone.
 */
export interface GetZoneArgs {
    readonly callerReference?: string;
    readonly comment?: string;
    readonly name?: string;
    readonly privateZone?: boolean;
    readonly resourceRecordSetCount?: number;
    readonly tags?: {[key: string]: any};
    readonly vpcId?: string;
    readonly zoneId?: string;
}

/**
 * A collection of values returned by getZone.
 */
export interface GetZoneResult {
    readonly callerReference: string;
    readonly comment: string;
    readonly name: string;
    readonly nameServers: string[];
    readonly resourceRecordSetCount: number;
    readonly tags: {[key: string]: any};
    readonly vpcId: string;
    readonly zoneId: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
