// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class DomainDkim extends pulumi.CustomResource {
    /**
     * Get an existing DomainDkim resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainDkimState, opts?: pulumi.CustomResourceOptions): DomainDkim {
        return new DomainDkim(name, <any>state, { ...opts, id: id });
    }

    public /*out*/ readonly dkimTokens: pulumi.Output<string[]>;
    public readonly domain: pulumi.Output<string>;

    /**
     * Create a DomainDkim resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainDkimArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainDkimArgs | DomainDkimState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: DomainDkimState = argsOrState as DomainDkimState | undefined;
            inputs["dkimTokens"] = state ? state.dkimTokens : undefined;
            inputs["domain"] = state ? state.domain : undefined;
        } else {
            const args = argsOrState as DomainDkimArgs | undefined;
            if (!args || args.domain === undefined) {
                throw new Error("Missing required property 'domain'");
            }
            inputs["domain"] = args ? args.domain : undefined;
            inputs["dkimTokens"] = undefined /*out*/;
        }
        super("aws:ses/domainDkim:DomainDkim", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DomainDkim resources.
 */
export interface DomainDkimState {
    readonly dkimTokens?: pulumi.Input<pulumi.Input<string>[]>;
    readonly domain?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DomainDkim resource.
 */
export interface DomainDkimArgs {
    readonly domain: pulumi.Input<string>;
}
