// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class SnapshotCopyGrant extends pulumi.CustomResource {
    /**
     * Get an existing SnapshotCopyGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SnapshotCopyGrantState, opts?: pulumi.CustomResourceOptions): SnapshotCopyGrant {
        return new SnapshotCopyGrant(name, <any>state, { ...opts, id: id });
    }

    public readonly kmsKeyId: pulumi.Output<string>;
    public readonly snapshotCopyGrantName: pulumi.Output<string>;
    public readonly tags: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a SnapshotCopyGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SnapshotCopyGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SnapshotCopyGrantArgs | SnapshotCopyGrantState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: SnapshotCopyGrantState = argsOrState as SnapshotCopyGrantState | undefined;
            inputs["kmsKeyId"] = state ? state.kmsKeyId : undefined;
            inputs["snapshotCopyGrantName"] = state ? state.snapshotCopyGrantName : undefined;
            inputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as SnapshotCopyGrantArgs | undefined;
            if (!args || args.snapshotCopyGrantName === undefined) {
                throw new Error("Missing required property 'snapshotCopyGrantName'");
            }
            inputs["kmsKeyId"] = args ? args.kmsKeyId : undefined;
            inputs["snapshotCopyGrantName"] = args ? args.snapshotCopyGrantName : undefined;
            inputs["tags"] = args ? args.tags : undefined;
        }
        super("aws:redshift/snapshotCopyGrant:SnapshotCopyGrant", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SnapshotCopyGrant resources.
 */
export interface SnapshotCopyGrantState {
    readonly kmsKeyId?: pulumi.Input<string>;
    readonly snapshotCopyGrantName?: pulumi.Input<string>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a SnapshotCopyGrant resource.
 */
export interface SnapshotCopyGrantArgs {
    readonly kmsKeyId?: pulumi.Input<string>;
    readonly snapshotCopyGrantName: pulumi.Input<string>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
}
