// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getVpcPeeringConnection(args?: GetVpcPeeringConnectionArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcPeeringConnectionResult> {
    args = args || {};
    return pulumi.runtime.invoke("aws:ec2/getVpcPeeringConnection:getVpcPeeringConnection", {
        "cidrBlock": args.cidrBlock,
        "filters": args.filters,
        "id": args.id,
        "ownerId": args.ownerId,
        "peerCidrBlock": args.peerCidrBlock,
        "peerOwnerId": args.peerOwnerId,
        "peerRegion": args.peerRegion,
        "peerVpcId": args.peerVpcId,
        "region": args.region,
        "status": args.status,
        "tags": args.tags,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcPeeringConnection.
 */
export interface GetVpcPeeringConnectionArgs {
    readonly cidrBlock?: string;
    readonly filters?: { name: string, values: string[] }[];
    readonly id?: string;
    readonly ownerId?: string;
    readonly peerCidrBlock?: string;
    readonly peerOwnerId?: string;
    readonly peerRegion?: string;
    readonly peerVpcId?: string;
    readonly region?: string;
    readonly status?: string;
    readonly tags?: {[key: string]: any};
    readonly vpcId?: string;
}

/**
 * A collection of values returned by getVpcPeeringConnection.
 */
export interface GetVpcPeeringConnectionResult {
    readonly accepter: {[key: string]: boolean};
    readonly cidrBlock: string;
    readonly id: string;
    readonly ownerId: string;
    readonly peerCidrBlock: string;
    readonly peerOwnerId: string;
    readonly peerRegion: string;
    readonly peerVpcId: string;
    readonly region: string;
    readonly requester: {[key: string]: boolean};
    readonly status: string;
    readonly tags: {[key: string]: any};
    readonly vpcId: string;
}
