// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getVpcEndpoint(args?: GetVpcEndpointArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcEndpointResult> {
    args = args || {};
    return pulumi.runtime.invoke("aws:ec2/getVpcEndpoint:getVpcEndpoint", {
        "id": args.id,
        "serviceName": args.serviceName,
        "state": args.state,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcEndpoint.
 */
export interface GetVpcEndpointArgs {
    readonly id?: string;
    readonly serviceName?: string;
    readonly state?: string;
    readonly vpcId?: string;
}

/**
 * A collection of values returned by getVpcEndpoint.
 */
export interface GetVpcEndpointResult {
    readonly cidrBlocks: string[];
    readonly dnsEntries: { dnsName: string, hostedZoneId: string }[];
    readonly id: string;
    readonly networkInterfaceIds: string[];
    readonly policy: string;
    readonly prefixListId: string;
    readonly privateDnsEnabled: boolean;
    readonly routeTableIds: string[];
    readonly securityGroupIds: string[];
    readonly serviceName: string;
    readonly state: string;
    readonly subnetIds: string[];
    readonly vpcEndpointType: string;
    readonly vpcId: string;
}
