// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getResource(args: GetResourceArgs, opts?: pulumi.InvokeOptions): Promise<GetResourceResult> {
    return pulumi.runtime.invoke("aws:apigateway/getResource:getResource", {
        "path": args.path,
        "restApiId": args.restApiId,
    }, opts);
}

/**
 * A collection of arguments for invoking getResource.
 */
export interface GetResourceArgs {
    readonly path: string;
    readonly restApiId: string;
}

/**
 * A collection of values returned by getResource.
 */
export interface GetResourceResult {
    readonly parentId: string;
    readonly pathPart: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
