# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Mapping, Optional, Tuple, Union
from .. import _utilities, _tables
from . import outputs

__all__ = [
    'ChannelHlsIngest',
    'ChannelHlsIngestIngestEndpoint',
]

@pulumi.output_type
class ChannelHlsIngest(dict):
    @property
    @pulumi.getter(name="ingestEndpoints")
    def ingest_endpoints(self) -> Optional[List['outputs.ChannelHlsIngestIngestEndpoint']]:
        """
        A list of the ingest endpoints
        """
        ...

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class ChannelHlsIngestIngestEndpoint(dict):
    @property
    @pulumi.getter
    def password(self) -> Optional[str]:
        """
        The password
        """
        ...

    @property
    @pulumi.getter
    def url(self) -> Optional[str]:
        """
        The URL
        """
        ...

    @property
    @pulumi.getter
    def username(self) -> Optional[str]:
        """
        The username
        """
        ...

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


