// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Stack extends pulumi.CustomResource {
    /**
     * Get an existing Stack resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StackState, opts?: pulumi.CustomResourceOptions): Stack {
        return new Stack(name, <any>state, { ...opts, id: id });
    }

    public readonly capabilities: pulumi.Output<string[] | undefined>;
    public readonly disableRollback: pulumi.Output<boolean | undefined>;
    public readonly iamRoleArn: pulumi.Output<string | undefined>;
    public readonly name: pulumi.Output<string>;
    public readonly notificationArns: pulumi.Output<string[] | undefined>;
    public readonly onFailure: pulumi.Output<string | undefined>;
    public /*out*/ readonly outputs: pulumi.Output<{[key: string]: any}>;
    public readonly parameters: pulumi.Output<{[key: string]: any}>;
    public readonly policyBody: pulumi.Output<string>;
    public readonly policyUrl: pulumi.Output<string | undefined>;
    public readonly tags: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly templateBody: pulumi.Output<string>;
    public readonly templateUrl: pulumi.Output<string | undefined>;
    public readonly timeoutInMinutes: pulumi.Output<number | undefined>;

    /**
     * Create a Stack resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StackArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StackArgs | StackState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: StackState = argsOrState as StackState | undefined;
            inputs["capabilities"] = state ? state.capabilities : undefined;
            inputs["disableRollback"] = state ? state.disableRollback : undefined;
            inputs["iamRoleArn"] = state ? state.iamRoleArn : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["notificationArns"] = state ? state.notificationArns : undefined;
            inputs["onFailure"] = state ? state.onFailure : undefined;
            inputs["outputs"] = state ? state.outputs : undefined;
            inputs["parameters"] = state ? state.parameters : undefined;
            inputs["policyBody"] = state ? state.policyBody : undefined;
            inputs["policyUrl"] = state ? state.policyUrl : undefined;
            inputs["tags"] = state ? state.tags : undefined;
            inputs["templateBody"] = state ? state.templateBody : undefined;
            inputs["templateUrl"] = state ? state.templateUrl : undefined;
            inputs["timeoutInMinutes"] = state ? state.timeoutInMinutes : undefined;
        } else {
            const args = argsOrState as StackArgs | undefined;
            inputs["capabilities"] = args ? args.capabilities : undefined;
            inputs["disableRollback"] = args ? args.disableRollback : undefined;
            inputs["iamRoleArn"] = args ? args.iamRoleArn : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["notificationArns"] = args ? args.notificationArns : undefined;
            inputs["onFailure"] = args ? args.onFailure : undefined;
            inputs["parameters"] = args ? args.parameters : undefined;
            inputs["policyBody"] = args ? args.policyBody : undefined;
            inputs["policyUrl"] = args ? args.policyUrl : undefined;
            inputs["tags"] = args ? args.tags : undefined;
            inputs["templateBody"] = args ? args.templateBody : undefined;
            inputs["templateUrl"] = args ? args.templateUrl : undefined;
            inputs["timeoutInMinutes"] = args ? args.timeoutInMinutes : undefined;
            inputs["outputs"] = undefined /*out*/;
        }
        super("aws:cloudformation/stack:Stack", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Stack resources.
 */
export interface StackState {
    readonly capabilities?: pulumi.Input<pulumi.Input<string>[]>;
    readonly disableRollback?: pulumi.Input<boolean>;
    readonly iamRoleArn?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly notificationArns?: pulumi.Input<pulumi.Input<string>[]>;
    readonly onFailure?: pulumi.Input<string>;
    readonly outputs?: pulumi.Input<{[key: string]: any}>;
    readonly parameters?: pulumi.Input<{[key: string]: any}>;
    readonly policyBody?: pulumi.Input<string>;
    readonly policyUrl?: pulumi.Input<string>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
    readonly templateBody?: pulumi.Input<string>;
    readonly templateUrl?: pulumi.Input<string>;
    readonly timeoutInMinutes?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Stack resource.
 */
export interface StackArgs {
    readonly capabilities?: pulumi.Input<pulumi.Input<string>[]>;
    readonly disableRollback?: pulumi.Input<boolean>;
    readonly iamRoleArn?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly notificationArns?: pulumi.Input<pulumi.Input<string>[]>;
    readonly onFailure?: pulumi.Input<string>;
    readonly parameters?: pulumi.Input<{[key: string]: any}>;
    readonly policyBody?: pulumi.Input<string>;
    readonly policyUrl?: pulumi.Input<string>;
    readonly tags?: pulumi.Input<{[key: string]: any}>;
    readonly templateBody?: pulumi.Input<string>;
    readonly templateUrl?: pulumi.Input<string>;
    readonly timeoutInMinutes?: pulumi.Input<number>;
}
