// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getComputeEnvironment(args: GetComputeEnvironmentArgs, opts?: pulumi.InvokeOptions): Promise<GetComputeEnvironmentResult> {
    return pulumi.runtime.invoke("aws:batch/getComputeEnvironment:getComputeEnvironment", {
        "computeEnvironmentName": args.computeEnvironmentName,
    }, opts);
}

/**
 * A collection of arguments for invoking getComputeEnvironment.
 */
export interface GetComputeEnvironmentArgs {
    readonly computeEnvironmentName: string;
}

/**
 * A collection of values returned by getComputeEnvironment.
 */
export interface GetComputeEnvironmentResult {
    readonly arn: string;
    readonly ecsClusterArn: string;
    readonly serviceRole: string;
    readonly state: string;
    readonly status: string;
    readonly statusReason: string;
    readonly type: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
